#!/usr/bin/env bash
# Build and deploy the Selkie contracts to a Stellar network.
#
#   ./scripts/deploy.sh                      # testnet, default identities
#   NETWORK=futurenet ./scripts/deploy.sh    # somewhere else
#
# Writes the deployed ids to contracts/deployments/<network>.env so the backend
# and the Stellar adapter can read them instead of hardcoding an address.
set -euo pipefail

NETWORK="${NETWORK:-testnet}"
ADMIN="${ADMIN:-selkie-admin}"
ORACLE="${ORACLE:-selkie-oracle}"

cd "$(dirname "$0")/.."
OUT_DIR="deployments"
OUT_FILE="$OUT_DIR/$NETWORK.env"

admin_addr=$(stellar keys address "$ADMIN")
oracle_addr=$(stellar keys address "$ORACLE")

echo "network : $NETWORK"
echo "admin   : $ADMIN ($admin_addr)"
echo "oracle  : $ORACLE ($oracle_addr)"
echo

echo "==> building"
stellar contract build

echo "==> deploying handle-escrow"
escrow_id=$(stellar contract deploy \
  --wasm target/wasm32v1-none/release/selkie_handle_escrow.wasm \
  --source "$ADMIN" \
  --network "$NETWORK" \
  -- \
  --admin "$admin_addr" \
  --oracle "$oracle_addr")

mkdir -p "$OUT_DIR"
cat > "$OUT_FILE" <<EOF
# Generated by contracts/scripts/deploy.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
SELKIE_NETWORK=$NETWORK
SELKIE_HANDLE_ESCROW_ID=$escrow_id
SELKIE_ADMIN_ADDRESS=$admin_addr
SELKIE_ORACLE_ADDRESS=$oracle_addr
EOF

echo
echo "handle-escrow: $escrow_id"
echo "wrote $OUT_FILE"
